### ISSUE TITLE
Marker detection taking >1 min, then failing

### ISSUE THREAD

**Issue by raghavauppuluri13** [duyipai/gsmini#1]
@duyipai When enabling shear force estimation, the gaussian filter in `markerdetection.py` seems to be taking a long time for me (1+ min): https://github.com/duyipai/gsmini/blob/eb043e314cede51ddb4178f2f8d218c1a4eff155/gsmini/markertracker.py#L41 takes a long time to run. my raw img and depth look like this: 
![image](https://github.com/duyipai/gsmini/assets/41026849/fac02012-0993-42df-b6c8-c0a3dddcb143)

then i get the following error:
```
  File "/home/aloha/interbotix_ws/src/gsmini/gsmini/gsdevice.py", line 126, in connect
    mtracker = MarkerTracker(np.float32(self._img) / 255.0)
  File "/home/aloha/interbotix_ws/src/gsmini/gsmini/markertracker.py", line 94, in __init__
    ) = self.assign_coordinates(sorted_centers)
  File "/home/aloha/interbotix_ws/src/gsmini/gsmini/markertracker.py", line 239, in assign_coordinates
    x0 = x_coords[idx]
IndexError: list index out of range
```

**Comment by duyipai** [comment]
Hi, Raghava. This part of the code is from the original GelSight, and I did not change anything. 
Interestingly, on my setup the condition [self.params["GridStyle"] == GridStyle.ALL](https://github.com/duyipai/gsmini/blob/eb043e314cede51ddb4178f2f8d218c1a4eff155/gsmini/markertracker.py#L86) evaluates `False` and then the `assign_coordinates` function is never called. Can you check why you have it as `True`?

**Comment by raghavauppuluri13** [comment]
unfortunately, it doesn't fix the delay issue and still doesn't work. i switched to optical flow here: https://github.com/duyipai/gsmini/pull/2/commits/4ab09f6ac7c38d598f0280492a1a2ac45c6eed6c in https://github.com/duyipai/gsmini/pull/2


I tested this and it works.
